### ISSUE TITLE
Allow perpendicular underground entrance/exit in front of empty splitter output

### ISSUE THREAD

**Issue by raynquist** [R-O-C-K-E-T/Factorio-SAT#3]
For balancers that contain empty splitter outputs (downsizing balancers), being able to place perpendicular underground entrance/exit next to such outputs is an important layout trick.  The splitters are prevented from side-loading onto the undergrounds by setting output filters, thus preserving the desired 2-1 splitter behavior.

Here is an example 6-2 balancer that beats Factorio-SAT's solution:
![image](https://user-images.githubusercontent.com/31404369/133036391-ed18b815-ff52-40c5-9e08-7c5d0e82fdd1.png)

The associated splitter output filters need not be in the program output; I can add them by hand.

Should this negatively impact performance, the functionality can be selectively enabled only for networks containing 2-1 splitters.  Conversely, similar configurations involving empty splitter inputs can also be selectively disabled for networks that do not contain 1-2 splitters if doing so improves performance.

**Comment by R-O-C-K-E-T** [comment]
It's very doable implementing this, empty splitter outputs already have special handling for a couple special configurations. I don't think it will make a significant performance difference, beyond the usual cost of adding extra possibilities.
