### ISSUE TITLE
Balancer solution longer than existing best

### ISSUE THREAD

**Issue by tcosprojects** [R-O-C-K-E-T/Factorio-SAT#4]
Hi, first off this project is amazing! During my testing I've found an output for the 8x3 balancer that is longer than what is in Raynquist's book. See the attached picture.

I can only guess why this might be, so I have some questions. Is Factorio-SAT exhaustive in its search of shorter balancers if it finds no solution? Or would this be a something to do with the constraints? Will Factorio-SAT allow a loop next to the exit belts like the current 8x3 best?

Thanks!

![8x3_comparison](https://user-images.githubusercontent.com/518742/164790154-e2088705-cbd8-4ca3-89d5-0459b3392a86.png)

**Comment by R-O-C-K-E-T** [comment]
Factorio-SAT does not exhaustively check every configuration of tiles. However, (assuming no bugs) it does *prove* whether or not a balancer is possible.

As for the loop next to the exit belt Factorio-SAT does not allow any non-empty tiles on the ends outside those needed for input/output. Unless using the new `--use-ends` option.
![40](https://user-images.githubusercontent.com/2784602/164844975-4a3b1093-c904-4513-bac4-4e320df98003.gif)
