### ISSUE TITLE
Question on how to use

### ISSUE THREAD

**Issue by frayien** [R-O-C-K-E-T/Factorio-SAT#9]
Hi ! I have a very specific problem, I am trying to design a 8 to 12 balancer with an L shape and specifically placed outputs.
I decided to give a try to your project because I love the idea of it but I have trouble understanding how to use it,
I want to define exactly where my inputs and outputs are and let the algorithm find a solution from that, 
Is it even possible ?

Thanks !

**Comment by R-O-C-K-E-T** [comment]
A 8-12 balancer uses 26 splitters which is a bit too large for Factorio-SAT to solve at once. You could break it up into two 4-6 balancers and provide them as a base with the `--partial` option. To use said option provide either a blueprint or json file.

`--partial` can also be used to set a specific input/output configuration. Unless you need inputs and outputs that are separated, which is currently not supported (though easy to implement).

**Comment by frayien** [comment]
I failed to use --partial because of the other issue I opened, but I used your app to generate a 4-6 to the dimensions I needed and an interchanger to link them with the help of a little manual tweaking. Works great. 

Amassing tool you made here, thanks !
